# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 37e7bc774b78ba1e38f4db64f6304a1e6983258015836c488add3bb4dbef8109780d425c9c0fce979ab3c8ff8954b7add7e750a52fcea6999380bd4e91eb1e82

test:
  secret_key_base: 726c283dbc624dc30c53052ccf14de527e8edfdddcfc63eb51bb2e9f342ccd0a6d65292d33fe3b1cecdb96bb759d4cccd9eb916ce1ce6e0a89c5627d99a36ae0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
